### ISSUE TITLE
Error: Cannot find module preinstall.js

### ISSUE THREAD

**Issue by epsilon42** [jackHedaya/pure-realtime-stock#2]
Hi there.

I'm having problems installing this, I receive the error below when installing using npm, and a similar error using yarn:

```
npm install --save pure-realtime-stock

> pure-realtime-stock@1.0.6 preinstall /Users/andrew/Sites/stockgrid/node_modules/pure-realtime-stock
> node ./preinstall.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/Users/andrew/Sites/stockgrid/node_modules/pure-realtime-stock/preinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/typescript-estree@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.14.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-realtime-stock@1.0.6 preinstall: `node ./preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-realtime-stock@1.0.6 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2019-07-26T18_01_10_640Z-debug.log
```

My setup is:
macOS Mojave 10.14.5
Node v12.7.0 (have also tried v10.15.1)

I've also installed puppeteer first as per an issue that someone else was experiencing.

Any ideas what else I should try?

**Comment by jackHedaya** [comment]
Hey! Thanks for reaching out!

I did some investigating and I believe the mistake is on my end. I did not add some required files to the package.json.

**Comment by jackHedaya** [comment]
Will release when I get to a computer.

**Comment by epsilon42** [comment]
Thanks @jackHedaya. 

FYI: the version on npm is 1.0.6 so is still problematic when trying to install from command line, but I was able to install successfully by adding GitHub repo to `package.json` to get latest version.
```
  "dependencies": {
    "pure-realtime-stock": "jackHedaya/pure-realtime-stock"
  },
```

**Comment by jackHedaya** [comment]
I’ve been having poor WiFi connection so I didn’t want to release until everything was tested.
