### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by Gh0s7** [jackHedaya/pure-realtime-stock#3]
Hi there, I just tried your library but I can't get it working.
Here's my log:

```
Subscribing to AAPL.
Error: Evaluation failed: TypeError: Cannot read property 'parentElement' of null
    at ExecutionContext._evaluateInternal (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\Page.js:827:43)
    at Page.<anonymous> (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\puppeteer\lib\helper.js:112:23)
    at RealtimeStock._run (A:\Users\steptnt@live.it\OneDrive\Desktop\tradeBotTest\node_modules\pure-realtime-stock\index.js:36:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Getting AAPL price failed. See 'logs' to get the error message
```

**Comment by jackHedaya** [comment]
Hey! Made a migration to Robinhood which should solve this problem. Let me know if this resolves your problem.
